# Credits

This is heavily influenced or copied from https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used. If you have a cuda enabled machine, read the README.md in the root of this repo on how to use nvidia-docker.


It’s a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [1]:
import torch

Construct a 5x3 matrix, uninitialized

In [2]:
x = torch.Tensor(5, 3)
print(x)

tensor([[1.8567e-01, 7.5553e+28, 5.2839e-11],
        [7.5018e+28, 2.5460e-12, 3.8473e-11],
        [7.1428e+31, 1.7466e+19, 1.4585e-19],
        [4.4721e+21, 7.2070e+22, 4.7428e+30],
        [7.9801e-10, 2.5171e-12, 1.4586e-19]])


Construct a randomly initialized matrix

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.6467, 0.6603, 0.8024],
        [0.9809, 0.5447, 0.2097],
        [0.6554, 0.6407, 0.0324],
        [0.6311, 0.4307, 0.6657],
        [0.3055, 0.8253, 0.1704]])


Get its size

In [4]:
print(x.size())

torch.Size([5, 3])


**NOTE** `torch.Size` is in fact a tuple, so it supports the same operations

In [5]:
x[1:3] = 2
print(x)

tensor([[0.6467, 0.6603, 0.8024],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.6311, 0.4307, 0.6657],
        [0.3055, 0.8253, 0.1704]])


# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [6]:
y = torch.rand(5, 3)
print(x + y)

tensor([[1.2552, 0.9251, 0.9133],
        [2.4125, 2.4914, 2.6030],
        [2.4118, 2.2148, 2.1666],
        [0.9650, 0.6570, 1.0785],
        [1.3020, 0.9894, 0.2042]])


### 2.2 Addition: syntax 2

In [7]:
print(torch.add(x, y))

tensor([[1.2552, 0.9251, 0.9133],
        [2.4125, 2.4914, 2.6030],
        [2.4118, 2.2148, 2.1666],
        [0.9650, 0.6570, 1.0785],
        [1.3020, 0.9894, 0.2042]])


### 2.3 Addition: giving an output tensor

In [8]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.2552, 0.9251, 0.9133],
        [2.4125, 2.4914, 2.6030],
        [2.4118, 2.2148, 2.1666],
        [0.9650, 0.6570, 1.0785],
        [1.3020, 0.9894, 0.2042]])


### 2.4 Addition: in-place

adds `x`to `y`

In [9]:
y.add_(x)
print(y)

tensor([[1.2552, 0.9251, 0.9133],
        [2.4125, 2.4914, 2.6030],
        [2.4118, 2.2148, 2.1666],
        [0.9650, 0.6570, 1.0785],
        [1.3020, 0.9894, 0.2042]])


**NOTE** Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [10]:
print(x[:, 1])

tensor([0.6603, 2.0000, 2.0000, 0.4307, 0.8253])


**Read later** 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiply of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))


In [30]:
a1 = torch.arange(3) # = [0, 1, 2]
b1 = torch.arange(3,6) # = [3, 4, 5]
a1.mul(b1)

tensor([ 0,  4, 10])

2. do the same, but inplace

In [34]:
a2 = torch.arange(3) # = [0, 1, 2]
b2 = torch.arange(3,6) # = [3, 4, 5]
a2.mul_(b2)
a2

tensor([ 0,  4, 10])

3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))

In [41]:
a3 = torch.arange(3.) # = [0, 1, 2]
b3 = torch.arange(3.,6.) # = [3, 4, 5]
a3.div(b3)

tensor([0.0000, 0.2500, 0.4000])

4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

In [45]:
a4 = torch.arange(2*4).reshape(2, 4)
b4 = torch.arange(4*2).reshape(4, 2)
a4.matmul(b4)

tensor([[28, 34],
        [76, 98]])

## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [11]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [12]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.

In [13]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [14]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a numpy array
3. now convert it back to a torch tensor

In [20]:
a1 = torch.ones(5, 2)
print("a1 = \n", a1)
a2 = a1.numpy()
print("a2 = \n", a2)
a3 = torch.from_numpy(a2)
print("a3 = \n", a3)

a1 = 
 tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
a2 = 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
a3 = 
 tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [15]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # this is meant as a tensor to be run on the GPU.
    # the .cuda() does this to any parameter it is applied to
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machie.")

tensor([[0.6467, 0.6603, 0.8024],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.6311, 0.4307, 0.6657],
        [0.3055, 0.8253, 0.1704]], device='cuda:0')
tensor([[1.2552, 0.9251, 0.9133],
        [2.4125, 2.4914, 2.6030],
        [2.4118, 2.2148, 2.1666],
        [0.9650, 0.6570, 1.0785],
        [1.3020, 0.9894, 0.2042]], device='cuda:0')
tensor([[1.9019, 1.5854, 1.7156],
        [4.4125, 4.4914, 4.6030],
        [4.4118, 4.2148, 4.1666],
        [1.5961, 1.0877, 1.7442],
        [1.6075, 1.8147, 0.3747]], device='cuda:0')
